service: aws-node-paystack-integration

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  # environment: ${file(env.yml):${self:provider.stage}}
  environment: ${file(env.yml)}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  incoming:
    handler: handler.main
    events:
      - http:
          path: paystack/incoming
          method: post
          cors: true
